DROP DATABASE IF EXISTS burger_cravings;
CREATE DATABASE burger_cravings;
USE burger_cravings;


/* Create a table for all your star wars characters */
CREATE TABLE burgers (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	burger_name VARCHAR( 255) NOT NULL,
    ts_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- ts_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE devoured (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	devoured_burger VARCHAR( 255) NOT NULL,
    ts_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- ts_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);